### ISSUE TITLE
define IRenderable

### ISSUE THREAD

**Issue by SmeTheWiz** [SmeTheWiz/Arcanum#9]
I want the interface to be simple, so below is initial concept. Internally we would need some state machine implementatation. Below is initial concept

Properties:
Height : integer/float, not sure if floating point is needed yet
Width : "
State : TRenderState (enum, internally needs to use a state machine)

Methods:
Render(ATarget:Tbitmap):boolean, can render if not already rendering, returns true if also rendered
Invalidate(), changes state to allow rendering again

**Comment by esmithcarepoint** [comment]
I want the interface to be simple, so below is initial concept. Internally we would need some state machine implementatation. Below is initial concept

Properties:
Height : integer/float, not sure if floating point is needed yet
Width : "
State : TRenderState (enum, internally needs to use a state machine)


Methods:
Render(ATarget:Tbitmap):boolean, can render if not already rendering, returns true if also rendered
Invalidate(), changes state to allow rendering again

**Comment by SmeTheWiz** [comment]
possibly can use this library when implementing
https://github.com/SirRufo/stateless/blob/master/Stateless/Stateless.pas
